### ISSUE TITLE
Velocities Parameter listed as optional, but seems it is required throughout the code

### ISSUE THREAD

**Issue by bernym12** [hanjq17/EGHN#1]
I noticed in `eghn.py` that the `velocity` parameter was listed as optional and while it does seem that is the case in the return from the `forward` function, that is not the case throughout the rest of that function as well as initialization of other parts of the network. More specifically, in the `PoolingNet` initialization on line 124, the `EquivariantScalarNet` on line 130, and the `EGMN` network on line 137, these should all actually have the `n_vector_input` param decremented by 1 as by removing the `velocity` input, that reduces the vectors by 1.

**Comment by hanjq17** [comment]
Thank you for raising the point! I am more than willing to modify the code in order to make `velocity` truly optional. I will update the code in a few days to reflect this issue.

**Comment by hanjq17** [comment]
I fixed this issue in the latest commit:
https://github.com/hanjq17/EGHN/commit/2152b979aa5034cbb372933c6f921ce020bd66bc

Thanks for the advice!

**Comment by bernym12** [comment]
Thanks so much for this!

> I fixed this issue in the latest commit: [2152b97](https://github.com/hanjq17/EGHN/commit/2152b979aa5034cbb372933c6f921ce020bd66bc)
> 
> Thanks for the advice!
